### ISSUE TITLE
minimap button

### ISSUE THREAD

**Issue by zimbabd** [fondlez/GroupBulletinBoard#2]
Hello, is it possible to add a button to the mini map in the future?

**Comment by fondlez** [comment]
There is already a minimap button. It looks like the icon for Priest's Prayer of Shadow Protection:
![groupbulletinboard-minimap-button](https://github.com/user-attachments/assets/43d324ba-e157-48e9-a88f-7ac081f05f5a)

The README instructions also already say:

> To open the settings, use slash command: /gbb or **click the minimap icon**.
